server:
  port: 8000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true  # 서비스 ID를 소문자로 처리
      routes:
        - id: user-service
          uri: lb://user-service  # 서비스 ID는 소문자로 변경
          predicates:
            - Path=/api/users/**

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
    registry-fetch-interval-seconds: 5
    fetch-registry: true
    register-with-eureka: true