spring:
  application:
    name: service-discovery

server:
  port: 8761

eureka:
  instance:
    hostname: service-discovery
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
