version: '3'
services:
  service-discovery:
    build: ./service-discovery
    ports:
      - "8761:8761"

  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - service-discovery

  user-service:
    build: ./user-service
    ports:
      - "8001:8001"
    depends_on:
      - service-discovery
