version: '3'
services:
  service-discovery:
    build: ./service-discovery
    container_name: service-discovery
    ports:
      - "8761:8761"
    networks:
      - service-net

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - service-discovery
    networks:
      - service-net

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8001:8001"
    depends_on:
      - service-discovery
    networks:
      - service-net

networks:
  service-net:
    driver: bridge
